import React from 'react';
import { WebsiteAuditReport } from '../types';
import { ExecutiveSummaryPanel } from './ExecutiveSummaryPanel';
import { TechnicalSeoPanel } from './TechnicalSeoPanel';
import { OnPageSeoPanel } from './OnPageSeoPanel';
import { CompetitorGapPanel } from './CompetitorGapPanel';
import { LocalSeoPanel } from './LocalSeoPanel';
import { AiRoadmapPanel } from './AiRoadmapPanel';
import { FileText, Printer, ArrowLeft, Download, ShieldCheck, Sparkles, Globe } from 'lucide-react';

interface PublicReportViewProps {
  report: WebsiteAuditReport;
  agencyName: string;
  logoLetter: string;
  themeColor: string;
}

export const PublicReportView: React.FC<PublicReportViewProps> = ({ 
  report, 
  agencyName, 
  logoLetter, 
  themeColor 
}) => {
  
  const handlePrint = () => {
    window.print();
  };

  const handleDownloadHtml = () => {
    // Generates a fully playable self-contained HTML offline document of this report!
    const htmlContent = `
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>${report.companyName} | SEO Audit Report | Generated by ${agencyName}</title>
        <script src="https://cdn.tailwindcss.com"></script>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
        <style>
          body { font-family: 'Inter', sans-serif; }
          @media print {
            .no-print { display: none !important; }
            body { background: white; color: black; }
          }
        </style>
      </head>
      <body class="bg-slate-50 text-slate-800 p-8 min-h-screen">
        <div class="max-w-5xl mx-auto space-y-8 bg-white p-10 rounded-3xl border border-slate-200 shadow-sm">
          <div class="flex items-center justify-between border-b pb-6">
            <div class="flex items-center gap-3">
              <div class="w-10 h-10 rounded-xl flex items-center justify-center text-white font-bold text-lg" style="background-color: ${themeColor}">
                ${logoLetter}
              </div>
              <div>
                <h1 class="text-xl font-bold">${agencyName}</h1>
                <p class="text-xs text-slate-400">Professional SEO Evaluation Suite</p>
              </div>
            </div>
            <div class="text-right">
              <span class="text-xs text-slate-500 font-mono">Date Generated</span>
              <p class="text-sm font-bold">${new Date(report.generatedAt).toLocaleDateString()}</p>
            </div>
          </div>

          <div class="space-y-3">
            <span class="bg-indigo-50 border border-indigo-150 text-indigo-700 font-mono text-[10px] px-3 py-1 rounded-full uppercase tracking-wider font-extrabold">Executive Valuation Proposal</span>
            <h2 class="text-2xl font-bold tracking-tight">${report.companyName}</h2>
            <p class="text-sm text-slate-500">Domain: <strong class="text-slate-800">${report.domain}</strong></p>
          </div>

          <div class="bg-slate-900 text-white rounded-2xl p-6 flex flex-col md:flex-row justify-between items-center gap-6">
            <div class="space-y-2">
              <h3 class="text-lg font-bold">Overall Search Optimization Score</h3>
              <p class="text-xs text-slate-300">Measured across core performance index, technical schema markup, and regional search presence.</p>
            </div>
            <div class="w-24 h-24 rounded-full border-4 border-indigo-500/25 flex items-center justify-center font-extrabold text-3xl font-mono text-indigo-400">
              ${report.overallScore}%
            </div>
          </div>

          <div class="prose max-w-none text-slate-700 leading-relaxed">
            <h3 class="text-lg font-bold text-slate-950 mb-2">Executive Summary</h3>
            <p class="text-sm">${report.executiveSummary}</p>
          </div>

          <div class="border-t pt-8 space-y-4">
            <h3 class="text-lg font-bold text-slate-950">Prioritized Technical Recommendations Checklist</h3>
            <div class="space-y-3">
              ${report.recommendations.map((rec, index) => `
                <div class="border rounded-xl p-4 bg-slate-50/50 flex flex-col gap-1.5">
                  <div class="flex items-center justify-between">
                    <span class="font-bold text-xs font-mono uppercase tracking-wider text-rose-600">${rec.priority} Priority</span>
                    <span class="text-xs font-medium text-slate-500 bg-slate-100 px-2.5 py-0.5 rounded-full">${rec.category}</span>
                  </div>
                  <h4 class="font-bold text-slate-900 text-sm">${rec.title}</h4>
                  <p class="text-xs text-slate-650">${rec.description}</p>
                  <p class="text-[11px] text-slate-400 italic">Impact: ${rec.impact}</p>
                </div>
              `).join('')}
            </div>
          </div>
          
          <div class="border-t pt-8 text-center text-xs text-slate-400 font-mono">
            Generated with ${agencyName} SEO Audit Suite &copy; ${new Date().getFullYear()}
          </div>
        </div>
      </body>
      </html>
    `;
    const element = document.createElement("a");
    const file = new Blob([htmlContent], { type: 'text/html' });
    element.href = URL.createObjectURL(file);
    element.download = `${report.domain}_seo_audit_report.html`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div id="public-report-view-root" className="min-h-screen bg-slate-50 text-slate-900 pb-16">
      
      {/* Upper floating print and download controller bar (no-print) */}
      <header className="sticky top-0 z-50 bg-white/95 backdrop-blur-md border-b border-slate-200 shadow-xs h-16 flex items-center justify-between px-6 md:px-12 no-print">
        <button
          type="button"
          onClick={() => {
            window.location.href = '/';
          }}
          className="flex items-center gap-1.5 text-xs font-bold text-slate-600 hover:text-slate-900 transition bg-slate-100 hover:bg-slate-200/80 px-3.5 py-2 rounded-xl border border-slate-250 cursor-pointer"
        >
          <ArrowLeft className="w-3.5 h-3.5" />
          Dashboard Home
        </button>

        <div className="flex items-center gap-3">
          <span className="hidden sm:inline bg-indigo-50 border border-indigo-150 text-indigo-700 text-[10px] font-mono font-extrabold uppercase py-1 px-2.5 rounded-full tracking-wider">
            Ready to Save / Export
          </span>
          <button
            type="button"
            onClick={handleDownloadHtml}
            className="flex items-center gap-1.5 bg-white border border-slate-250 hover:bg-slate-50 transition px-4 py-2 rounded-xl text-xs font-bold text-slate-800 shadow-xs cursor-pointer active:scale-95"
          >
            <Download className="w-3.5 h-3.5 text-slate-500" />
            Download Offline HTML Report
          </button>
          
          <button
            type="button"
            onClick={handlePrint}
            className="flex items-center gap-1.5 bg-slate-900 hover:bg-slate-800 transition px-4 py-2 rounded-xl text-xs font-bold text-white shadow-md active:scale-95 cursor-pointer"
          >
            <Printer className="w-3.5 h-3.5 text-indigo-300" />
            Print / Save as PDF
          </button>
        </div>
      </header>

      {/* Main Single Page Printable Report Space */}
      <div className="max-w-5xl mx-auto px-6 md:px-12 pt-8 space-y-10">
        
        {/* Printable White-Label header block */}
        <div className="bg-white border border-slate-200 rounded-3xl p-6 md:p-10 shadow-xs flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
          <div className="flex items-center gap-4">
            <div 
              className="w-12 h-12 rounded-2xl flex items-center justify-center text-white font-extrabold text-2xl shadow-sm tracking-widest shrink-0"
              style={{ backgroundColor: themeColor }}
            >
              {logoLetter}
            </div>
            <div className="space-y-1">
              <h1 className="text-xl font-bold font-display text-slate-900 tracking-tight">{agencyName}</h1>
              <p className="text-xs text-slate-400 font-mono uppercase tracking-wider font-extrabold">Professional Client Performance Proposal</p>
            </div>
          </div>
          
          <div className="text-left md:text-right font-mono text-xs">
            <span className="text-slate-450 block text-[9px] uppercase tracking-wider font-medium">Generation Date</span>
            <span className="text-slate-800 font-bold text-xs">{new Date(report.generatedAt).toLocaleString()}</span>
          </div>
        </div>

        {/* Hero Score Box */}
        <div className="bg-gradient-to-r from-indigo-950 to-slate-900 text-white rounded-3xl p-6 md:p-10 shadow-lg border border-indigo-900 flex flex-col md:flex-row justify-between items-center gap-8 relative overflow-hidden">
          <div className="absolute right-0 top-0 w-48 h-48 bg-indigo-500/10 rounded-full blur-2xl pointer-events-none" />
          
          <div className="space-y-3 relative z-10 max-w-xl text-center md:text-left">
            <span className="bg-indigo-500/20 text-indigo-300 font-mono text-[9px] px-2.5 py-1 rounded-full border border-indigo-500/30 uppercase tracking-widest font-extrabold w-fit block mx-auto md:mx-0">
              Enterprise SEO Audit Index
            </span>
            <h2 className="text-2xl font-bold tracking-tight font-display text-white">
              Organic Performance Valuation Report
            </h2>
            <p className="text-indigo-200 text-xs leading-relaxed font-normal">
              Digital performance diagnostic prepared for <strong className="text-white font-bold">{report.companyName}</strong>. This evaluation indices technical speed budgets, crawlability, search visibility overlap, content markers, and local citation coherence metrics.
            </p>
          </div>

          <div className="flex flex-col items-center shrink-0 relative z-10 space-y-1">
            <span className="text-[10px] uppercase font-mono text-indigo-300 font-extrabold tracking-wider">Overall Score</span>
            <div className="w-28 h-28 rounded-full border-4 border-indigo-500/35 flex items-center justify-center font-black text-4xl text-indigo-300 bg-indigo-950 shadow-md shadow-indigo-950 font-mono">
              {report.overallScore}%
            </div>
            <span className="text-[9px] bg-indigo-500/30 text-indigo-200 px-2 py-0.5 rounded font-mono font-medium">
              Enterprise PRO Verified
            </span>
          </div>
        </div>

        {/* Diagnostic workspace tabs renders everything expanded so it is printable */}
        <div className="space-y-10">
          
          {/* Section: Executive Summary content */}
          <div className="bg-white border border-slate-200 rounded-3xl p-6 md:p-8 shadow-xs space-y-4">
            <h3 className="text-md font-bold font-display text-slate-900 border-b pb-3 flex items-center gap-2">
              <FileText className="w-5 h-5 text-indigo-550" />
              I. Executive Performance & Valuation Summary
            </h3>
            <p className="text-slate-700 leading-relaxed text-sm font-normal text-slate-755">
              {report.executiveSummary}
            </p>
          </div>

          {/* Section: Prioritized Technical Audit Checklists */}
          <div className="bg-white border border-slate-200 rounded-3xl p-6 md:p-8 shadow-xs space-y-6">
            <h3 className="text-md font-bold font-display text-slate-900 border-b pb-3 flex items-center gap-2">
              <ShieldCheck className="w-5 h-5 text-indigo-550" />
              II. Core Web Vitals & Technical Speed Diagnostics
            </h3>
            <TechnicalSeoPanel report={report} />
          </div>

          {/* Section: Onpage SEO Content */}
          <div className="bg-white border border-slate-200 rounded-3xl p-6 md:p-8 shadow-xs space-y-6">
            <h3 className="text-md font-bold font-display text-slate-900 border-b pb-3 flex items-center gap-2">
              <Sparkles className="w-5 h-5 text-indigo-550" />
              III. On-Page Search Content Optimization
            </h3>
            <OnPageSeoPanel report={report} />
          </div>

          {/* Section: Competitors Backlink Gaps */}
          <div className="bg-white border border-slate-200 rounded-3xl p-6 md:p-8 shadow-xs space-y-6">
            <h3 className="text-md font-bold font-display text-slate-900 border-b pb-3 flex items-center gap-2">
              <Globe className="w-5 h-5 text-indigo-550" />
              IV. Competitor Organic Authority & Deficit Gaps
            </h3>
            <CompetitorGapPanel report={report} />
          </div>

          {/* Section: Local SEO GBP check if enabled */}
          {report.localSeo?.isApplicable && (
            <div className="bg-white border border-slate-200 rounded-3xl p-6 md:p-8 shadow-xs space-y-6">
              <h3 className="text-md font-bold font-display text-slate-900 border-b pb-3 flex items-center gap-2">
                <Globe className="w-5 h-5 text-indigo-550" />
                V. Google Maps GBP Coherence & Citations
              </h3>
              <LocalSeoPanel report={report} />
            </div>
          )}

          {/* Section: Actionable Prioritized AI Remediation Checklist */}
          <div className="bg-white border border-slate-200 rounded-3xl p-6 md:p-8 shadow-xs space-y-6">
            <h3 className="text-md font-bold font-display text-slate-900 border-b pb-3 flex items-center gap-2">
              <Sparkles className="w-5 h-5 text-indigo-550" />
              VI. Strategic Priority Remediation Blueprint
            </h3>
            <AiRoadmapPanel report={report} />
          </div>

        </div>

        {/* Base Footer brand */}
        <footer className="text-center text-slate-400 text-xs font-mono pt-8 border-t border-slate-200">
          Proposal generated via {agencyName} Core Spiders &copy; {new Date().getFullYear()}
        </footer>

      </div>

    </div>
  );
};
